# Generated by Django 4.2 on 2023-09-22 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='product.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('location', models.IntegerField()),
                ('price', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('is_banned', models.BooleanField()),
                ('updated_at', models.TimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='product.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
    ]
